MovieApp/MovieApp.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Web.Data;
using MovieApp.Web.Models;
using System.Collections.Generic;
using System.Linq;

namespace MovieApp.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly MovieContext _context;
        public HomeController(MovieContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var model = new HomePageViewModel
            {
                PopularMovies = _context.Movies.ToList()
            };

            return View(model);
        }

        public IActionResult About()
        {
            return View();
        }
    }
}

MovieApp/MovieApp.Web/ViewComponents/GenresViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Web.Data;
using MovieApp.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Web.ViewComponents
{
    public class GenresViewComponent: ViewComponent
    {
        private readonly MovieContext _context;
        public GenresViewComponent(MovieContext context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedGenre = RouteData.Values["id"];

            return View(_context.Genres.ToList());
        }
    }
}

MovieApp/MovieApp.Web/Views/Home/About.cshtml
@model List<Genre>


<p>
    Home/About
</p>

@section menu
{
    @*@await Html.PartialAsync("_menu", Model)*@
    @await Component.InvokeAsync("Genres")
}

MovieApp/MovieApp.Web/Views/Home/Index.cshtml
@model HomePageViewModel


@section header
{
    @await Html.PartialAsync("_header")
}
@section scripts {
    <script src="~/js/script.js"></script>
}


<h1>Film Listesi</h1>
<div id="filmler">
    @foreach (var movie in Model.PopularMovies)
    {
        @await Html.PartialAsync("_movie", movie)
    }
</div>